# Generated by Django 5.2 on 2025-04-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_japan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placesmodel',
            name='image',
        ),
    ]
